# From_Simple_to_Advanced_Data_Science

In [16]:
a=7

def square(a):
      return a ** 2
print(a **2)

49


In [25]:
import math
from math import pi
math.sin(pi/3)


0.8660254037844386

In [26]:
math.cos(pi/3)


0.5000000000000001

In [27]:
math.sin(pi/6)


0.49999999999999994

In [28]:
math.cos(pi/6)


0.8660254037844387

In [29]:
print(In[27])

math.sin(pi/6)


In [30]:
import numpy as np
np.array([1,23,4,5,7])

array([ 1, 23,  4,  5,  7])

In [39]:
np.arange(0, 2, 0.5)

array([0. , 0.5, 1. , 1.5])

In [42]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
np.random.random((3,3))

array([[0.28727509, 0.00129669, 0.62480986],
       [0.56479967, 0.82846865, 0.70651269],
       [0.68264721, 0.75579399, 0.71404938]])

In [48]:
np.random.normal(0, 1, (3, 3))

array([[ 0.52709564, -0.02815416, -0.60793473],
       [ 0.4071479 ,  1.46941203,  1.85945246],
       [-1.2538263 ,  0.48236115, -0.5807065 ]])

In [49]:
np.random.randint(0, 10, (3, 3))

array([[6, 9, 7],
       [9, 8, 0],
       [7, 6, 1]])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))


In [54]:
print("x3dim", x3.ndim)
print("x3shape",x3.shape)
print("x3size",x3.size)


x3dim 3
x3shape (3, 4, 5)
x3size 60


In [55]:
x1

array([5, 0, 3, 3, 7, 9])

In [57]:
x1[5]

9

In [63]:
x1[-1]

9

In [64]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [65]:
x3[0,0,0]

8

In [71]:
x3[2,3,3]

6

In [73]:
np.arange(20,0, -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [76]:
x1[4:]

array([7, 9])

In [82]:
x3[:2]

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]]])

In [84]:
x1 [5:7]

array([9])